### ISSUE TITLE
logo for rimau waf

### ISSUE THREAD

**Issue by asklinux** [asklinux/rimau-waf#1]
open for any proposal

**Comment by pislissniflis** [comment]
My simple proposal
![rimauwaf](https://user-images.githubusercontent.com/3725003/26892006-83f31ece-4be9-11e7-995a-247ac0dc69dd.png)

**Comment by mfazliazran** [comment]
At least kene letak gambar rimau skit set dia tengah berguling ke atas ayat rimau tu ke atau logo bentuk bulat baru nampak ada class skit huhuhu

**Comment by mfazliazran** [comment]
![6bd552cf25f3d721a878d7f3d1835723](https://user-images.githubusercontent.com/506827/26910822-e5ba7682-4c3b-11e7-8373-e7a96b64da70.jpg)
![165653480](https://user-images.githubusercontent.com/506827/26910825-e5c6e2e6-4c3b-11e7-9397-2cc30062d9f3.jpg)
![harimau logo](https://user-images.githubusercontent.com/506827/26910823-e5bf16f6-4c3b-11e7-9c69-9857f1973c6f.png)

![images](https://user-images.githubusercontent.com/506827/26910824-e5c6d77e-4c3b-11e7-87a4-c4e66a0eea32.png)
![picture1419756688817](https://user-images.githubusercontent.com/506827/26910826-e5c8421c-4c3b-11e7-9e05-8d534a5fe709.jpg)
![tiger](https://user-images.githubusercontent.com/506827/26910827-e5e6b3b4-4c3b-11e7-8deb-f233cfd5b075.jpg)
![tiger-309218_640](https://user-images.githubusercontent.com/506827/26910828-e6022806-4c3b-11e7-89f9-336dab546feb.png)
![tiger-head-icon-material-3688](https://user-images.githubusercontent.com/506827/26910829-e603268e-4c3b-11e7-888d-1a7ee36b6ce7.jpg)
![tiger-head-logo-painting-56756](https://user-images.githubusercontent.com/506827/26910830-e60bc2bc-4c3b-11e7-9bdf-16cf3ccbe1b9.jpg)
![3e9dcfa52f46be80bbcacc536e1757c9](https://user-images.githubusercontent.com/506827/26910831-e611fab0-4c3b-11e7-8711-c5ea3fc981a5.jpg)

**Comment by asklinux** [comment]
kalau ada gambar rimau lagi lawa la .. :D

**Comment by pislissniflis** [comment]
Hari-hari mau

**Comment by asklinux** [comment]
![screen shot 2017-06-17 at 8 34 26 pm](https://user-images.githubusercontent.com/4355917/27252948-ad7eb91e-539c-11e7-9418-23493c44b3bb.png)

**Comment by asklinux** [comment]
amacam design aku hihi

**Comment by mfazliazran** [comment]
ok la tu janji ada logo... ko kene buat jugak logo bulat sekali bro

**Comment by pislissniflis** [comment]
Terclosed. Haha
