### ISSUE TITLE
Problem Installing WAF

### ISSUE THREAD

**Issue by arun81** [asklinux/rimau-waf#12]
Hi Sir
Good Day..
We are getting below error while installing WAF
===========================================================
Transaction Summary
========================================================================================================================================================================
Install  1 Package (+21 Dependent packages)

Total size: 84 M
Total download size: 77 M
Installed size: 121 M
Is this ok [y/d/N]: y
Downloading packages:
rimauwaf-1.3.0-3.noarch.rpm    FAILED                                          ======================================================-] 200 kB/s |  77 MB  00:00:00 ETA
http://centos.tunnelbiz.com/7/x86_64/RPMS/rimauwaf-1.3.0-3.noarch.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=tunnelbiz clean metadata
Trying other mirror.

Error downloading packages:
  rimauwaf-1.3.0-3.noarch: [Errno 256] No more mirrors to try.

Please assist 

Thanks

**Comment by asklinux** [comment]
can u try back

**Comment by arun81** [comment]
Ok . I am trying the same . Will let you know with the updates . 

Anyways thanks 

Thanks

**Comment by arun81** [comment]
Web Page is opening perfectely 

But there is no option for enabling ModSecurity ON 

Attached Screenshot
![rimau-waf](https://user-images.githubusercontent.com/13440263/43337103-5ca15590-91f0-11e8-887e-7d4a82fb71a3.png)

**Comment by arun81** [comment]
Please I am closing this ticket as console is working fine 

Thanks
